#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_7,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_8,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393, PIDControl, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           RightDrive,    tmotorVex393, PIDControl, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port4,           LeftArm,    tmotorVex393, PIDControl, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port5,           RightArm,   tmotorVex393, PIDControl, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port6,           LeftShovel,    tmotorVex393, PIDControl, encoder, encoderPort, I2C_5, 1000)
#pragma config(Motor,  port7,           RightShovel,   tmotorVex393, PIDControl, encoder, encoderPort, I2C_6, 1000)
#pragma config(Motor,  port8,           LeftPaddle,    tmotorVex393, PIDControl, encoder, encoderPort, I2C_7, 1000)
#pragma config(Motor,  port9,           RightPaddle,   tmotorVex393, PIDControl, encoder, encoderPort, I2C_8, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
TODO:
> Add stuff for paddle
> Learn how to start tasks
> Learn how to use top buttons on controller
> Win States
*/
task drive1();
task basket1();
void drivercontrol();
task main(){
  StartTask(drive1);
  StartTask(basket1);
	drivercontrol();
}


task drive1(){
	while (true){
	//Drive
	motor[LeftDrive] = vexRT[Ch3];
	motor[RightDrive] = vexRT[Ch2];
		//All Stop
	if (vexRT[Btn8U] == 1){
				motor[LeftDrive] = 0;
				motor[LeftArm] = 0;
				motor[LeftShovel] = 0;
				motor[LeftPaddle] = 0;
				motor[RightDrive] = 0;
				motor[RightArm] = 0;
				motor[RightShovel] = 0;
				motor[RightPaddle] = 0;
	}
}
}

task basket1(){
	while (true){
		//Manual Shovel (warning: a lot of torque)
	while (vexRT[Btn5U] == 1){
		motor[LeftShovel] = 80;
		motor[RightShovel] = 80;
	}
	motor[LeftShovel] = 0;
	motor[RightShovel] = 0;
	while (vexRT[Btn5D] == 1){
		motor[LeftShovel] = -80;
		motor[RightShovel] = -80;
	}
	motor[LeftShovel] = 0;
	motor[RightShovel] = 0;
}
}


void drivercontrol(){ //Driver Controlled
	while (true){

	//Paddle
	//Grab Balls
	if (vexRT[Btn8D] == 1){
		motor[LeftPaddle] = 100;
		motor[RightPaddle] = -100;
}
	//Throw Balls
	if (vexRT[Btn8L] == 1){
		motor[LeftPaddle] = -100;
		motor[RightPaddle] = 100;
}
	//Stop Paddles
	if (vexRT[Btn8R] == 1){
		motor[LeftPaddle] = 0;
		motor[RightPaddle] = 0;
}


	//Arms
	while (vexRT[Btn6U] == 1){
		motor[LeftArm] = 127;
		motor[RightArm] = 127;
	}
	motor[LeftArm] = 0;
	motor[RightArm] = 0;
	while (vexRT[Btn6D] == 1){
		motor[LeftArm] = -127;
		motor[RightArm] = -127;
	}
	motor[LeftArm] = 0;
	motor[RightArm] = 0;
	}
}
