#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  DArmEncoders,   sensorTouch)
#pragma config(Sensor, dgtl2,  DWheelEncoders, sensorTouch)
#pragma config(Sensor, I2C_1,  encoder_RDrive, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  encoder_LDrive, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  encoder_LArm,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  encoder_RArm,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  encoder_Bucket, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           LDrive,        tmotorVex393_HBridge, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port3,           RArm,          tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port4,           Bucket,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_5)
#pragma config(Motor,  port5,           LPaddle,       tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           RPaddle,       tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LArm,          tmotorVex393_MC29, PIDControl, encoderPort, I2C_3)
#pragma config(Motor,  port10,          RDrive,        tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////
#pragma platform(VEX)																			//
#pragma competitionControl(Competition)										//
#pragma autonomousDuration(20)														//	<---Main Competition Code
#pragma userControlDuration(120)													//				!!DO NOT MODIFY!!
#include "Tracy_&_McKenney's_Vex_Competition_Includes.c"	//
#include "Tracy_&_McKenney's_Vex_LCD_Includes.h"					//
////////////////////////////////////////////////////////////



void pre_auton()
{
  bStopTasksBetweenModes = false;	//Set bStopTasksBetweenModes to true to stop all tasks immediately before and after autonomous and user control.
  																//It is recommended to set bStopTasksBetweenModes to true right before the competition.
	resetAllEncoders();	//Resets all motor encoders. This will not work if you are using the standard "Vex_Competition_Includes" file.

	program0 = "Program";
	program1 = "Program";
	program2 = "Program";
	program3 = "Program";
	program4 = "Program";	//Name your autonomous programs here. The numbers here match the case numbers in autonomous.
	program5 = "Program";
	program6 = "Program";
	program7 = "Program";
	program8 = "Program";
	program9 = "Program";

	startTask(lcdScreen);	//start lcd program selection task
}
task autonomous()
{
	clearTimer(T1);	//start autonomous timer
	autonReset:
	switch(autonProgramSelect)
	{
		case 0:

		break;
		case 1:

		break;
		case 2:

		break;
		case 3:

		break;
		case 4:

		break;
		case 5:

		break;
		case 6:

		break;
		case 7:

		break;
		case 8:

		break;
		case 9:

		break;
		default:
			autonProgramSelect = 0;
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDPos(0,0);
			displayNextLCDString(program0);
			displayNextLCDString(" ");
			displayNextLCDNumber(autonProgramSelect);
			displayLCDCenteredString(1,"Running as Default");
			goto autonReset;	//restart autonomous segment
		break;
	}
}	//end of autonomous

task usercontrol()
{
	while(true)
	{
		//driver control code here
	}
}	//End of driver control
