#pragma config(Motor,  port1,           LeftForwardMotorA, tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, None)
#pragma config(Motor,  port2,           LeftMiddleMotorA, tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, None)
#pragma config(Motor,  port3,           LeftRearMotorA, tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, None)
#pragma config(Motor,  port4,           LeftForwardMotorD, tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port5,           LeftRearMotorD, tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port6,           RightForwardMotorD, tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, None)
#pragma config(Motor,  port7,           RightRearMotorD, tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, None)
#pragma config(Motor,  port8,           RightForwardMotorA, tmotorVex393_HBridge, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port9,           RightMiddleMotorA, tmotorVex393_HBridge, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port10,          RightRearMotorA, tmotorVex393_HBridge, openLoop, driveRight, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
VEX Robotics Source Code
See License (../../LICENSE.TXT)
*/

task main()
{
	while(true){
		//Emergency Motor Stop
		if (vexRT[Btn8D] == 1){
		motor[LeftForwardMotorA] = 0;
		motor[LeftForwardMotorD] = 0;
		motor[LeftMiddleMotorA] = 0;
		motor[LeftRearMotorA] = 0;
		motor[RightForwardMotorA] = 0;
		motor[RightForwardMotorD] = 0;
		motor[RightMiddleMotorA] = 0;
		motor[RightRearMotorA] = 0;
		motor[RightRearMotorD] = 0;
		wait1Msec(5000); //wait 5 sec
		}
		//Slave Mapping
		//LeftForwardMotorD is Master for Driver
		motor[RightForwardMotorD] = motor[LeftForwardMotorD];
		motor[RightRearMotorD] = motor[LeftForwardMotorD];
		motor[LeftRearMotorD] = motor[LeftForwardMotorD];
		//LeftMiddleMotorA is Master for Arm
		motor[RightForwardMotorA] = motor[LeftMiddleMotorA];
		motor[RightRearMotorA] = motor[LeftMiddleMotorA];
		motor[LeftRearMotorA] = motor[LeftMiddleMotorA];
		//End Slave

		//User Input
		motor[LeftForwardMotorD] = vexRT[Ch1]; //<-- Add threshold?


	}
}
